name: Deploy to ScreenCraft via FTP

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './'
          # Target directory, e.g. public_html or public_html/api
          remote_path: ${{ secrets.SFTP_REMOTE_DIR }}
          delete_remote_files: false
          rsyncArgs: '--exclude=node_modules --exclude=.git* --exclude=.github --exclude=tests --exclude=coverage --exclude=storage/framework/** --exclude=storage/logs'
          sftpArgs: '-o ConnectTimeout=3600'

      - name: Trigger deploy hook (migrate + cache)
        env:
          DEPLOY_HOOK_TOKEN: ${{ secrets.DEPLOY_HOOK_TOKEN }}
          DEPLOY_SITE_URL: ${{ secrets.DEPLOY_SITE_URL }}
        run: |
          curl -sS -X POST \
            -H "X-Deploy-Token: ${DEPLOY_HOOK_TOKEN}" \
            "${DEPLOY_SITE_URL%/}/deploy-hook" || exit 1