name: Deploy to ScreenCraft via FTP

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          local-dir: ./
          # Target directory, e.g. public_html or public_html/api
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          timeout-minutes: 15 # time out after 15 minutes
          exclude: |
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**
            **/coverage/**

      - name: Trigger deploy hook (migrate + cache)
        env:
          DEPLOY_HOOK_TOKEN: ${{ secrets.DEPLOY_HOOK_TOKEN }}
          DEPLOY_SITE_URL: ${{ secrets.DEPLOY_SITE_URL }}
        run: |
          curl -sS -X POST \
            -H "X-Deploy-Token: ${DEPLOY_HOOK_TOKEN}" \
            "${DEPLOY_SITE_URL%/}/deploy-hook" || exit 1